const input = document.getElementById('input');
const output = document.getElementById('output');
const obfuscateBtn = document.getElementById('obfuscateBtn');
const copyBtn = document.getElementById('copyBtn');
const strengthSelect = document.getElementById('strength');

function simpleObfuscate(code, strength) {
    let result = code;

    // Basic renaming + junk
    result = result.replace(/local/g, 'l_');
    result = result.replace(/function/g, 'f_');

    if (strength === 'strong' || strength === 'extreme') {
        result = result.split('').map(char => {
            if (Math.random() > 0.7) return '\\x' + char.charCodeAt(0).toString(16);
            return char;
        }).join('');
    }

    if (strength === 'extreme') {
        result = 'local _ = function() ' + result + ' end; return _()';
    }

    return '-- Generated by Crackus Free Obfuscator\n\n' + result;
}

obfuscateBtn.addEventListener('click', () => {
    const code = input.value.trim();
    if (!code) return alert('Paste some code first');

    const strength = strengthSelect.value;
    const obfuscated = simpleObfuscate(code, strength);

    output.value = obfuscated;
});

copyBtn.addEventListener('click', () => {
    if (output.value) {
        navigator.clipboard.writeText(output.value);
        copyBtn.textContent = 'Copied!';
        setTimeout(() => copyBtn.textContent = 'Copy Obfuscated Code', 2000);
    }
});
